// "use client"

import { Providers } from '../redux/provider'
import './globals.css'
// import {useState,useEffect} from 'react'
// import { Inter } from 'next/font/google'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const [mounted, setMounted] = useState(false);
  // useEffect(() => setMounted(true), []);
  return (
    <Providers >
      <html lang="en">
        <body>{children}</body>
      </html>
    </Providers>
  )
}
