import LeftSideMainPage from '@/src/components/mainPage/leftSideMainPage'
import '../globals.css'
import RightSideMainPage from '@/src/components/mainPage/rightSideMainPage'
// import { Inter } from 'next/font/google'


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function Layout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="grid grid-cols-[repeat(16,_minmax(0,_1fr))] gap-[2px] bg-bgColorLight dark:bg-bgColorDark">
            <div className="col-span-4 leftSideMainPage">
                <LeftSideMainPage />
            </div>
            <div className="col-span-12 rightSideMainPage">
                {children}
            </div>
        </div>
    )
}
