import LeftSideMainPage from '@/src/components/mainPage/leftSideMainPage'
import '../globals.css'
import RightSideMainPage from '@/src/components/mainPage/rightSideMainPage'
// import { Inter } from 'next/font/google'


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function Layout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="grid 
        lg:grid-cols-[repeat(16,_minmax(0,_1fr))]  
        md:grid-cols-[repeat(16,_minmax(0,_1fr))] 
        grid-cols-12
        bg-bgColorLight gap-[2px]
        dark:bg-bgColorDark">
            <div className="
            md:col-span-4
            sm:col-span-2
            col-span-12
            leftSideMainPage">
                <LeftSideMainPage />
            </div>
            <div className="
            md:col-span-12
            sm:col-span-14
            col-span-12
            rightSideMainPage">
                {children}
            </div>
        </div>
    )
}
